#!/usr/bin/env python3
"""Generate the sim's lightweight IR-18-inspired OBJ assets.

Coordinates match the renderer convention:
  X = lateral, Y = up, Z = forward.
"""

import math
from pathlib import Path


ASSET_DIR = Path("assets/meshes")


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def mul(a, scalar):
    return (a[0] * scalar, a[1] * scalar, a[2] * scalar)


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def length(a):
    return math.sqrt(max(dot(a, a), 0.0))


def normalize(a):
    mag = length(a)
    if mag < 1.0e-6:
        return (0.0, 1.0, 0.0)
    return (a[0] / mag, a[1] / mag, a[2] / mag)


def face_normal(points):
    if len(points) < 3:
        return (0.0, 1.0, 0.0)
    return normalize(cross(sub(points[2], points[0]), sub(points[1], points[0])))


class OBJWriter:
    def __init__(self, title):
        self.title = title
        self.vertices = []
        self.normals = []
        self.faces = []
        self.current_material = None

    def add_vertex(self, point):
        self.vertices.append(point)
        return len(self.vertices)

    def add_normal(self, normal):
        self.normals.append(normalize(normal))
        return len(self.normals)

    def set_material(self, material):
        self.current_material = material

    def add_face(self, points, material, normals=None):
        if len(points) < 3:
            return
        self.set_material(material)
        if normals is None:
            normal_index = self.add_normal(face_normal(points))
            normal_indices = [normal_index for _ in points]
        else:
            normal_indices = [self.add_normal(normal) for normal in normals]
        vertex_indices = [self.add_vertex(point) for point in points]
        self.faces.append((vertex_indices, normal_indices, self.current_material))

    def add_tri(self, a, b, c, material, normal=None):
        normals = None if normal is None else [normal, normal, normal]
        self.add_face([a, b, c], material, normals)

    def add_quad(self, a, b, c, d, material, normal=None):
        normals = None if normal is None else [normal, normal, normal, normal]
        self.add_face([a, b, c, d], material, normals)

    def write(self, path):
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as file:
            file.write(f"# {self.title}\n")
            file.write("# Generated by scripts/generate_geometry.py\n")
            for vertex in self.vertices:
                file.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
            for normal in self.normals:
                file.write(f"vn {normal[0]:.6f} {normal[1]:.6f} {normal[2]:.6f}\n")

            last_material = None
            for vertex_indices, normal_indices, material in self.faces:
                if material != last_material:
                    file.write(f"usemtl {material}\n")
                    last_material = material
                tokens = [
                    f"{vertex_index}//{normal_index}"
                    for vertex_index, normal_index in zip(vertex_indices, normal_indices)
                ]
                file.write(f"f {' '.join(tokens)}\n")


def add_box(writer, min_point, max_point, material):
    x0, y0, z0 = min_point
    x1, y1, z1 = max_point
    writer.add_quad((x0, y0, z0), (x0, y1, z0), (x1, y1, z0), (x1, y0, z0), material, (0, 0, -1))
    writer.add_quad((x1, y0, z1), (x1, y1, z1), (x0, y1, z1), (x0, y0, z1), material, (0, 0, 1))
    writer.add_quad((x0, y0, z1), (x0, y1, z1), (x0, y1, z0), (x0, y0, z0), material, (-1, 0, 0))
    writer.add_quad((x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1), material, (1, 0, 0))
    writer.add_quad((x0, y0, z1), (x0, y0, z0), (x1, y0, z0), (x1, y0, z1), material, (0, -1, 0))
    writer.add_quad((x0, y1, z0), (x0, y1, z1), (x1, y1, z1), (x1, y1, z0), material, (0, 1, 0))


def add_rect_loft(writer, sections, material):
    """Loft rectangular sections. Each section has z, cx, half_width, y_min, y_max."""
    rings = []
    for section in sections:
        z = section["z"]
        cx = section.get("cx", 0.0)
        half_width = section["half_width"]
        y_min = section["y_min"]
        y_max = section["y_max"]
        rings.append(
            [
                (cx - half_width, y_min, z),
                (cx + half_width, y_min, z),
                (cx + half_width, y_max, z),
                (cx - half_width, y_max, z),
            ]
        )

    for index in range(len(rings) - 1):
        a = rings[index]
        b = rings[index + 1]
        writer.add_quad(a[0], b[0], b[1], a[1], material)
        writer.add_quad(a[1], b[1], b[2], a[2], material)
        writer.add_quad(a[2], b[2], b[3], a[3], material)
        writer.add_quad(a[3], b[3], b[0], a[0], material)

    first = rings[0]
    last = rings[-1]
    writer.add_quad(first[0], first[1], first[2], first[3], material)
    writer.add_quad(last[3], last[2], last[1], last[0], material)


def add_ellipse_loft(writer, sections, material, segments=36, cap=True):
    rings = []
    normals = []
    for section in sections:
        z = section["z"]
        cx = section.get("cx", 0.0)
        cy = section["cy"]
        rx = section["rx"]
        ry = section["ry"]
        ring = []
        normal_ring = []
        for index in range(segments):
            angle = 2.0 * math.pi * index / segments
            ca = math.cos(angle)
            sa = math.sin(angle)
            ring.append((cx + rx * ca, cy + ry * sa, z))
            normal_ring.append(normalize((ca / max(rx, 0.001), sa / max(ry, 0.001), 0.0)))
        rings.append(ring)
        normals.append(normal_ring)

    for section_index in range(len(rings) - 1):
        for index in range(segments):
            next_index = (index + 1) % segments
            writer.add_face(
                [
                    rings[section_index][index],
                    rings[section_index + 1][index],
                    rings[section_index + 1][next_index],
                    rings[section_index][next_index],
                ],
                material,
                [
                    normals[section_index][index],
                    normals[section_index + 1][index],
                    normals[section_index + 1][next_index],
                    normals[section_index][next_index],
                ],
            )

    if cap:
        rear_center = (sections[0].get("cx", 0.0), sections[0]["cy"], sections[0]["z"])
        front_center = (sections[-1].get("cx", 0.0), sections[-1]["cy"], sections[-1]["z"])
        for index in range(segments):
            next_index = (index + 1) % segments
            writer.add_tri(rear_center, rings[0][next_index], rings[0][index], material, (0, 0, -1))
            writer.add_tri(front_center, rings[-1][index], rings[-1][next_index], material, (0, 0, 1))


def add_trapezoid_plate_x(writer, x_center, thickness, yz_points, material):
    x0 = x_center - thickness * 0.5
    x1 = x_center + thickness * 0.5
    left = [(x0, y, z) for y, z in yz_points]
    right = [(x1, y, z) for y, z in yz_points]
    writer.add_face(left, material, [(-1, 0, 0) for _ in left])
    writer.add_face(list(reversed(right)), material, [(1, 0, 0) for _ in right])
    for index in range(len(yz_points)):
        next_index = (index + 1) % len(yz_points)
        writer.add_quad(left[index], left[next_index], right[next_index], right[index], material)


def add_airfoil(writer, z_rear, z_front, half_span_rear, half_span_front, y_rear, y_front, thickness, material):
    bottom_offset = -thickness * 0.45
    top_offset = thickness * 0.55
    sections = [
        {
            "z": z_rear,
            "cx": 0.0,
            "half_width": half_span_rear,
            "y_min": y_rear + bottom_offset,
            "y_max": y_rear + top_offset,
        },
        {
            "z": z_front,
            "cx": 0.0,
            "half_width": half_span_front,
            "y_min": y_front + bottom_offset,
            "y_max": y_front + top_offset,
        },
    ]
    add_rect_loft(writer, sections, material)


def add_cylinder_between(writer, start, end, radius, material, segments=10):
    direction = sub(end, start)
    axis = normalize(direction)
    if length(direction) < 1.0e-5:
        return
    reference = (0.0, 1.0, 0.0)
    if abs(dot(axis, reference)) > 0.92:
        reference = (1.0, 0.0, 0.0)
    u_axis = normalize(cross(reference, axis))
    v_axis = normalize(cross(axis, u_axis))

    start_ring = []
    end_ring = []
    normals = []
    for index in range(segments):
        angle = 2.0 * math.pi * index / segments
        radial = add(mul(u_axis, math.cos(angle)), mul(v_axis, math.sin(angle)))
        start_ring.append(add(start, mul(radial, radius)))
        end_ring.append(add(end, mul(radial, radius)))
        normals.append(radial)

    for index in range(segments):
        next_index = (index + 1) % segments
        writer.add_face(
            [start_ring[index], end_ring[index], end_ring[next_index], start_ring[next_index]],
            material,
            [normals[index], normals[index], normals[next_index], normals[next_index]],
        )

    for index in range(segments):
        next_index = (index + 1) % segments
        writer.add_tri(start, start_ring[next_index], start_ring[index], material, mul(axis, -1.0))
        writer.add_tri(end, end_ring[index], end_ring[next_index], material, axis)


def add_revolved_profile_x(writer, profile, material, segments=64):
    rings = []
    normal_rings = []
    for profile_index, (x, radius) in enumerate(profile):
        ring = []
        normal_ring = []
        prev_x, prev_r = profile[max(0, profile_index - 1)]
        next_x, next_r = profile[min(len(profile) - 1, profile_index + 1)]
        slope_x = next_x - prev_x
        slope_r = next_r - prev_r
        for index in range(segments):
            angle = 2.0 * math.pi * index / segments
            sa = math.sin(angle)
            ca = math.cos(angle)
            ring.append((x, radius * sa, radius * ca))
            normal_ring.append(normalize((-slope_r, slope_x * sa, slope_x * ca)))
        rings.append(ring)
        normal_rings.append(normal_ring)

    for profile_index in range(len(profile) - 1):
        for index in range(segments):
            next_index = (index + 1) % segments
            writer.add_face(
                [
                    rings[profile_index][index],
                    rings[profile_index + 1][index],
                    rings[profile_index + 1][next_index],
                    rings[profile_index][next_index],
                ],
                material,
                [
                    normal_rings[profile_index][index],
                    normal_rings[profile_index + 1][index],
                    normal_rings[profile_index + 1][next_index],
                    normal_rings[profile_index][next_index],
                ],
            )


def add_cylinder_x(writer, width, radius, material, segments=64):
    half_width = width * 0.5
    profile = [(-half_width, 0.0), (-half_width, radius), (half_width, radius), (half_width, 0.0)]
    add_revolved_profile_x(writer, profile, material, segments)


def add_steering_arc(writer, radius_x, radius_y, start_degrees, end_degrees, material, radius=0.018, segments=18):
    last = None
    for index in range(segments + 1):
        t = index / segments
        angle = math.radians(start_degrees + (end_degrees - start_degrees) * t)
        point = (math.cos(angle) * radius_x, math.sin(angle) * radius_y, 0.0)
        if last is not None:
            add_cylinder_between(writer, last, point, radius, material, 8)
        last = point


def generate_car_mesh():
    writer = OBJWriter("IR-18-inspired open-wheel car mesh")

    length_m = 5.123
    width_m = 1.943
    front_axle_z = 1.300
    rear_axle_z = front_axle_z - 3.035
    front_limit_z = length_m * 0.5
    rear_limit_z = -length_m * 0.5
    half_width = width_m * 0.5

    # Carbon floor and diffuser: wide enough to read as an Indycar undertray without hiding the wheels.
    add_rect_loft(
        writer,
        [
            {"z": -1.55, "half_width": 0.68, "y_min": 0.055, "y_max": 0.080},
            {"z": -1.30, "half_width": 0.76, "y_min": 0.055, "y_max": 0.080},
            {"z": -0.35, "half_width": 0.62, "y_min": 0.058, "y_max": 0.120},
            {"z": 1.42, "half_width": 0.38, "y_min": 0.060, "y_max": 0.112},
            {"z": 2.12, "half_width": 0.115, "y_min": 0.064, "y_max": 0.102},
        ],
        "carbon_floor",
    )
    for x in (-0.46, -0.23, 0.23, 0.46):
        add_rect_loft(
            writer,
            [
                {"z": rear_limit_z + 0.18, "cx": x, "half_width": 0.018, "y_min": 0.080, "y_max": 0.275},
                {"z": -1.55, "cx": x * 1.10, "half_width": 0.014, "y_min": 0.070, "y_max": 0.130},
            ],
            "carbon_diffuser",
        )
        
    add_rect_loft(
        writer,
        [
            {"z": rear_limit_z + 0.05, "half_width": 0.14, "y_min": 0.22, "y_max": 0.33},
            {"z": -1.85, "half_width": 0.22, "y_min": 0.20, "y_max": 0.38},
        ],
        "carbon_attenuator",
    )

    # Stretched wedge body and very low nose.
    add_ellipse_loft(
        writer,
        [
            {"z": -2.16, "cy": 0.315, "rx": 0.070, "ry": 0.072},
            {"z": -1.72, "cy": 0.405, "rx": 0.195, "ry": 0.155},
            {"z": -1.04, "cy": 0.470, "rx": 0.285, "ry": 0.205},
            {"z": -0.44, "cy": 0.500, "rx": 0.340, "ry": 0.195},
            {"z": 0.18, "cy": 0.455, "rx": 0.275, "ry": 0.150},
            {"z": 0.88, "cy": 0.330, "rx": 0.165, "ry": 0.082},
            {"z": 1.60, "cy": 0.235, "rx": 0.082, "ry": 0.046},
            {"z": 2.32, "cy": 0.170, "rx": 0.035, "ry": 0.024},
        ],
        "paint",
        segments=40,
    )
    add_rect_loft(
        writer,
        [
            {"z": 0.66, "half_width": 0.130, "y_min": 0.145, "y_max": 0.300},
            {"z": 1.64, "half_width": 0.070, "y_min": 0.115, "y_max": 0.215},
            {"z": 2.34, "half_width": 0.026, "y_min": 0.100, "y_max": 0.162},
        ],
        "paint_accent",
    )

    # Compact, tapered sidepods with clear open-wheel separation.
    for side in (-1.0, 1.0):
        add_rect_loft(
            writer,
            [
                {"z": 0.22, "cx": side * 0.395, "half_width": 0.130, "y_min": 0.155, "y_max": 0.355},
                {"z": -0.45, "cx": side * 0.470, "half_width": 0.160, "y_min": 0.150, "y_max": 0.450},
                {"z": -1.34, "cx": side * 0.390, "half_width": 0.115, "y_min": 0.160, "y_max": 0.335},
            ],
            "paint_dark",
        )
        add_box(
            writer,
            (side * 0.590 - (0.030 if side > 0.0 else 0.0), 0.285, -0.72),
            (side * 0.590 + (0.030 if side < 0.0 else 0.0), 0.440, -0.10),
            "carbon_intake",
        )
        add_cylinder_between(
            writer,
            (side * 0.505, 0.555, -0.34),
            (side * 0.705, 0.630, -0.42),
            0.015,
            "carbon_mirror_stalk",
            8,
        )
        add_box(writer, (side * 0.710 - 0.055, 0.615, -0.485), (side * 0.710 + 0.055, 0.665, -0.385), "carbon_mirror")

    # Cockpit tub, driver helmet, visor, and halo.
    add_box(writer, (-0.285, 0.558, -0.58), (0.285, 0.612, 0.060), "carbon_cockpit_opening")
    add_ellipse_loft(
        writer,
        [
            {"z": -0.47, "cy": 0.735, "rx": 0.135, "ry": 0.110},
            {"z": -0.31, "cy": 0.765, "rx": 0.150, "ry": 0.130},
            {"z": -0.17, "cy": 0.740, "rx": 0.125, "ry": 0.110},
        ],
        "paint_accent_helmet",
        segments=24,
    )
    add_box(writer, (-0.120, 0.790, -0.46), (0.120, 0.875, -0.230), "visor_glass")
    add_cylinder_between(writer, (-0.315, 0.640, 0.035), (-0.125, 0.920, -0.465), 0.020, "carbon_halo", 10)
    add_cylinder_between(writer, (0.315, 0.640, 0.035), (0.125, 0.920, -0.465), 0.020, "carbon_halo", 10)
    add_cylinder_between(writer, (-0.125, 0.920, -0.465), (0.125, 0.920, -0.465), 0.020, "carbon_halo", 10)
    add_cylinder_between(writer, (0.0, 0.610, 0.050), (0.0, 0.920, -0.465), 0.018, "carbon_halo", 10)
    add_box(writer, (-0.065, 0.700, -0.760), (0.065, 0.985, -0.535), "carbon_roll_hoop")

    # Featherweight front wing: wide, low, and blade-like with tiny tapered end treatments.
    add_airfoil(writer, 2.230, front_limit_z, half_width * 0.86, half_width, 0.105, 0.088, 0.042, "carbon_front_wing")
    add_airfoil(writer, 2.080, 2.305, half_width * 0.63, half_width * 0.78, 0.205, 0.170, 0.032, "paint_accent_front_flap")
    for side in (-1.0, 1.0):
        add_trapezoid_plate_x(
            writer,
            side * half_width,
            0.024,
            [(0.060, 2.235), (0.205, 2.160), (0.240, 2.515), (0.086, front_limit_z)],
            "carbon_front_wing_endplate",
        )
        add_cylinder_between(writer, (side * 0.455, 0.195, 2.06), (side * 0.185, 0.240, 1.58), 0.011, "suspension_arm", 8)

    # Compact tail, tensioned rear wing, and integrated diffuser pipes.
    add_rect_loft(
        writer,
        [
            {"z": -1.50, "half_width": 0.250, "y_min": 0.255, "y_max": 0.520},
            {"z": -2.25, "half_width": 0.120, "y_min": 0.245, "y_max": 0.390},
        ],
        "paint_dark_tail",
    )
    add_airfoil(writer, rear_limit_z + 0.190, rear_limit_z + 0.500, 0.520, 0.590, 0.780, 0.815, 0.052, "carbon_rear_wing")
    add_airfoil(writer, rear_limit_z + 0.290, rear_limit_z + 0.470, 0.460, 0.535, 0.915, 0.935, 0.034, "paint_accent_rear_flap")
    for side in (-1.0, 1.0):
        add_trapezoid_plate_x(
            writer,
            side * 0.610,
            0.022,
            [(0.735, rear_limit_z + 0.190), (0.955, rear_limit_z + 0.250), (0.950, rear_limit_z + 0.500), (0.790, rear_limit_z + 0.535)],
            "carbon_rear_wing_endplate",
        )
        add_cylinder_between(writer, (side * 0.170, 0.350, -2.12), (side * 0.375, 0.790, -2.20), 0.014, "carbon_rear_wing_support", 8)
    add_box(writer, (-0.325, 0.360, rear_limit_z + 0.230), (0.325, 0.435, rear_limit_z + 0.310), "brake_light")
    for x in (-0.070, 0.070):
        add_cylinder_between(writer, (x, 0.315, -2.22), (x, 0.315, rear_limit_z + 0.030), 0.038, "metal_exhaust", 12)

    # Visual suspension pickup detail. Animated wishbones are drawn in Metal, these fixed pieces add density.
    for side in (-1.0, 1.0):
        for z_axle, front in ((front_axle_z, True), (rear_axle_z, False)):
            hub_x = side * (0.84 if front else 0.80)
            inner_x = side * (0.245 if front else 0.310)
            bias = 1.0 if front else -1.0
            add_cylinder_between(writer, (inner_x, 0.410, z_axle + 0.250 * bias), (hub_x, 0.400, z_axle + 0.110 * bias), 0.014, "suspension_arm", 8)
            add_cylinder_between(writer, (inner_x, 0.292, z_axle - 0.210 * bias), (hub_x, 0.275, z_axle - 0.080 * bias), 0.014, "suspension_arm", 8)
            add_cylinder_between(writer, (side * 0.140, 0.565, z_axle - 0.035 * bias), (hub_x, 0.430, z_axle), 0.011, "suspension_pushrod", 8)
            add_box(
                writer,
                (hub_x - 0.055, 0.345, z_axle - 0.090),
                (hub_x + 0.055, 0.500, z_axle + 0.090),
                "caliper_metal",
            )

    return writer


def generate_wheel_mesh():
    writer = OBJWriter("IR-18 rear-size wheel and tire mesh")
    half_width = 0.356 * 0.5
    tire_radius = 0.343
    bead_radius = 0.205
    add_revolved_profile_x(
        writer,
        [
            (-half_width, bead_radius),
            (-half_width, 0.296),
            (-half_width + 0.022, 0.325),
            (-0.092, tire_radius),
            (0.092, tire_radius),
            (half_width - 0.022, 0.325),
            (half_width, 0.296),
            (half_width, bead_radius),
        ],
        "tire",
        80,
    )
    for groove_x in (-0.105, -0.035, 0.035, 0.105):
        add_revolved_profile_x(
            writer,
            [(groove_x - 0.006, tire_radius + 0.002), (groove_x + 0.006, tire_radius + 0.002)],
            "tire_tread",
            80,
        )

    add_revolved_profile_x(
        writer,
        [
            (-0.150, 0.082),
            (-0.172, 0.185),
            (-0.150, 0.207),
            (0.150, 0.207),
            (0.172, 0.185),
            (0.150, 0.082),
        ],
        "rim_metal",
        64,
    )
    add_cylinder_x(writer, 0.052, 0.235, "brake_disc", 64)
    add_cylinder_x(writer, 0.105, 0.076, "hub_metal", 40)

    for face_x in (-0.180, 0.180):
        for index in range(12):
            angle = 2.0 * math.pi * index / 12.0
            start = (face_x * 0.92, math.sin(angle) * 0.054, math.cos(angle) * 0.054)
            end = (face_x, math.sin(angle) * 0.178, math.cos(angle) * 0.178)
            add_cylinder_between(writer, start, end, 0.0085, "spoke_metal", 8)
    return writer


def generate_steering_wheel_mesh():
    writer = OBJWriter("Open-wheel yoke steering wheel mesh")
    add_steering_arc(writer, 0.205, 0.125, 205.0, 335.0, "tire_grip", 0.020, 20)
    add_steering_arc(writer, 0.205, 0.125, 25.0, 155.0, "tire_grip", 0.018, 20)
    add_cylinder_between(writer, (-0.185, -0.052, 0.0), (-0.070, -0.012, 0.0), 0.012, "spoke_metal", 8)
    add_cylinder_between(writer, (0.185, -0.052, 0.0), (0.070, -0.012, 0.0), 0.012, "spoke_metal", 8)
    add_cylinder_between(writer, (-0.155, 0.082, 0.0), (-0.070, 0.032, 0.0), 0.010, "spoke_metal", 8)
    add_cylinder_between(writer, (0.155, 0.082, 0.0), (0.070, 0.032, 0.0), 0.010, "spoke_metal", 8)
    add_box(writer, (-0.078, -0.045, -0.024), (0.078, 0.052, 0.024), "paint_dark")
    add_box(writer, (-0.050, -0.020, -0.028), (0.050, 0.025, -0.022), "visor_glass")
    add_box(writer, (-0.112, -0.060, -0.020), (-0.086, -0.025, 0.020), "metal_blue_button")
    add_box(writer, (0.086, -0.060, -0.020), (0.112, -0.025, 0.020), "metal_yellow_button")
    add_box(writer, (-0.035, 0.060, -0.018), (-0.012, 0.084, 0.018), "metal_green_button")
    add_box(writer, (0.012, 0.060, -0.018), (0.035, 0.084, 0.018), "metal_red_button")
    return writer


def report_bounds(name, writer):
    xs = [vertex[0] for vertex in writer.vertices]
    ys = [vertex[1] for vertex in writer.vertices]
    zs = [vertex[2] for vertex in writer.vertices]
    print(
        f"{name}: {len(writer.vertices)} vertices, "
        f"bounds X {min(xs):.3f}..{max(xs):.3f}, "
        f"Y {min(ys):.3f}..{max(ys):.3f}, "
        f"Z {min(zs):.3f}..{max(zs):.3f}"
    )


def main():
    car = generate_car_mesh()
    wheel = generate_wheel_mesh()
    steering_wheel = generate_steering_wheel_mesh()

    car.write(ASSET_DIR / "car.obj")
    wheel.write(ASSET_DIR / "wheel.obj")
    steering_wheel.write(ASSET_DIR / "steering_wheel.obj")

    report_bounds("car.obj", car)
    report_bounds("wheel.obj", wheel)
    report_bounds("steering_wheel.obj", steering_wheel)


if __name__ == "__main__":
    main()
