#!/usr/bin/env python3
"""Generate detailed procedural OBJ meshes for the native Metal prototype.

The renderer intentionally avoids licensed third-party assets. This script
keeps the art pipeline reproducible while producing smoother car/wheel meshes
than the small fallback geometry compiled into the renderer.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Iterable, Optional


ROOT = Path(__file__).resolve().parents[1]
MESH_DIR = ROOT / "assets" / "meshes"


def add(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def mul(a: tuple[float, float, float], s: float) -> tuple[float, float, float]:
    return (a[0] * s, a[1] * s, a[2] * s)


def dot(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def length(v: tuple[float, float, float]) -> float:
    return math.sqrt(max(dot(v, v), 1.0e-12))


def norm(v: tuple[float, float, float]) -> tuple[float, float, float]:
    inv = 1.0 / length(v)
    return (v[0] * inv, v[1] * inv, v[2] * inv)


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


class Mesh:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.normals: list[tuple[float, float, float]] = []
        self.faces: list[tuple[str, tuple[tuple[int, int], tuple[int, int], tuple[int, int]]]] = []

    def vertex(self, position: tuple[float, float, float], normal: tuple[float, float, float]) -> tuple[int, int]:
        self.vertices.append(position)
        self.normals.append(norm(normal))
        index = len(self.vertices)
        return index, index

    def tri(
        self,
        material: str,
        a: tuple[float, float, float],
        b: tuple[float, float, float],
        c: tuple[float, float, float],
        normals: Optional[tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]] = None,
    ) -> None:
        if normals is None:
            face_normal = norm(cross(sub(c, a), sub(b, a)))
            normals = (face_normal, face_normal, face_normal)
        self.faces.append((material, (self.vertex(a, normals[0]), self.vertex(b, normals[1]), self.vertex(c, normals[2]))))

    def quad(
        self,
        material: str,
        a: tuple[float, float, float],
        b: tuple[float, float, float],
        c: tuple[float, float, float],
        d: tuple[float, float, float],
        normals: Optional[tuple[
            tuple[float, float, float],
            tuple[float, float, float],
            tuple[float, float, float],
            tuple[float, float, float],
        ]] = None,
    ) -> None:
        if normals is None:
            face_normal = norm(cross(sub(c, a), sub(b, a)))
            normals = (face_normal, face_normal, face_normal, face_normal)
        self.tri(material, a, b, c, (normals[0], normals[1], normals[2]))
        self.tri(material, a, c, d, (normals[0], normals[2], normals[3]))

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as file:
            file.write("# Generated by scripts/generate_high_poly_meshes.py\n")
            for x, y, z in self.vertices:
                file.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            for x, y, z in self.normals:
                file.write(f"vn {x:.6f} {y:.6f} {z:.6f}\n")
            current_material = ""
            for material, corners in self.faces:
                if material != current_material:
                    file.write(f"usemtl {material}\n")
                    current_material = material
                a, b, c = corners
                file.write(f"f {a[0]}//{a[1]} {b[0]}//{b[1]} {c[0]}//{c[1]}\n")


def ring_loft(
    mesh: Mesh,
    material: str,
    stations: Iterable[tuple[float, float, float, float]],
    segments: int,
    offset_x: float = 0.0,
) -> None:
    rings: list[list[tuple[tuple[float, float, float], tuple[float, float, float]]]] = []
    station_list = list(stations)
    for z, center_y, radius_x, radius_y in station_list:
        ring = []
        for index in range(segments):
            theta = math.tau * index / segments
            x = offset_x + math.cos(theta) * radius_x
            y = center_y + math.sin(theta) * radius_y
            normal = norm((math.cos(theta) / max(radius_x, 0.001), math.sin(theta) / max(radius_y, 0.001), 0.0))
            ring.append(((x, y, z), normal))
        rings.append(ring)

    for station in range(len(rings) - 1):
        for index in range(segments):
            next_index = (index + 1) % segments
            a, na = rings[station][index]
            b, nb = rings[station][next_index]
            c, nc = rings[station + 1][next_index]
            d, nd = rings[station + 1][index]
            mesh.quad(material, a, b, c, d, (na, nb, nc, nd))

    for station_index, z_normal in ((0, -1.0), (len(rings) - 1, 1.0)):
        center = (
            offset_x,
            station_list[station_index][1],
            station_list[station_index][0],
        )
        ring = rings[station_index]
        for index in range(segments):
            next_index = (index + 1) % segments
            if z_normal < 0.0:
                mesh.tri(material, center, ring[next_index][0], ring[index][0], ((0.0, 0.0, z_normal),) * 3)
            else:
                mesh.tri(material, center, ring[index][0], ring[next_index][0], ((0.0, 0.0, z_normal),) * 3)


def box(mesh: Mesh, material: str, minimum: tuple[float, float, float], maximum: tuple[float, float, float]) -> None:
    x0, x1 = sorted((minimum[0], maximum[0]))
    y0, y1 = sorted((minimum[1], maximum[1]))
    z0, z1 = sorted((minimum[2], maximum[2]))
    p000 = (x0, y0, z0)
    p001 = (x0, y0, z1)
    p010 = (x0, y1, z0)
    p011 = (x0, y1, z1)
    p100 = (x1, y0, z0)
    p101 = (x1, y0, z1)
    p110 = (x1, y1, z0)
    p111 = (x1, y1, z1)
    mesh.quad(material, p001, p101, p111, p011)
    mesh.quad(material, p100, p000, p010, p110)
    mesh.quad(material, p000, p001, p011, p010)
    mesh.quad(material, p101, p100, p110, p111)
    mesh.quad(material, p010, p011, p111, p110)
    mesh.quad(material, p000, p100, p101, p001)


def cylinder_between(
    mesh: Mesh,
    material: str,
    start: tuple[float, float, float],
    end: tuple[float, float, float],
    radius: float,
    segments: int = 16,
    cap: bool = True,
) -> None:
    axis = norm(sub(end, start))
    seed = (0.0, 1.0, 0.0) if abs(axis[1]) < 0.92 else (1.0, 0.0, 0.0)
    side = norm(cross(seed, axis))
    up = norm(cross(axis, side))
    start_ring = []
    end_ring = []
    for index in range(segments):
        theta = math.tau * index / segments
        radial = norm(add(mul(side, math.cos(theta)), mul(up, math.sin(theta))))
        start_ring.append((add(start, mul(radial, radius)), radial))
        end_ring.append((add(end, mul(radial, radius)), radial))
    for index in range(segments):
        next_index = (index + 1) % segments
        a, na = start_ring[index]
        b, nb = end_ring[index]
        c, nc = end_ring[next_index]
        d, nd = start_ring[next_index]
        mesh.quad(material, a, b, c, d, (na, nb, nc, nd))
    if cap:
        for index in range(segments):
            next_index = (index + 1) % segments
            mesh.tri(material, start, start_ring[index][0], start_ring[next_index][0], (mul(axis, -1.0),) * 3)
            mesh.tri(material, end, end_ring[next_index][0], end_ring[index][0], (axis,) * 3)


def uv_sphere(
    mesh: Mesh,
    material: str,
    center: tuple[float, float, float],
    radius: tuple[float, float, float],
    lat_segments: int = 16,
    lon_segments: int = 32,
    theta_min: float = 0.0,
    theta_max: float = math.tau,
    phi_min: float = -math.pi * 0.5,
    phi_max: float = math.pi * 0.5,
) -> None:
    grid: list[list[tuple[tuple[float, float, float], tuple[float, float, float]]]] = []
    for lat in range(lat_segments + 1):
        phi = phi_min + (phi_max - phi_min) * lat / lat_segments
        row = []
        for lon in range(lon_segments + 1):
            theta = theta_min + (theta_max - theta_min) * lon / lon_segments
            local = (math.cos(phi) * math.cos(theta), math.sin(phi), math.cos(phi) * math.sin(theta))
            position = (
                center[0] + local[0] * radius[0],
                center[1] + local[1] * radius[1],
                center[2] + local[2] * radius[2],
            )
            normal = norm((local[0] / max(radius[0], 0.001), local[1] / max(radius[1], 0.001), local[2] / max(radius[2], 0.001)))
            row.append((position, normal))
        grid.append(row)
    for lat in range(lat_segments):
        for lon in range(lon_segments):
            a, na = grid[lat][lon]
            b, nb = grid[lat][lon + 1]
            c, nc = grid[lat + 1][lon + 1]
            d, nd = grid[lat + 1][lon]
            mesh.quad(material, a, b, c, d, (na, nb, nc, nd))


def wing_panel(
    mesh: Mesh,
    material: str,
    z_center: float,
    y_center: float,
    span: float,
    chord: float,
    camber: float,
    angle: float,
    span_segments: int = 24,
    chord_segments: int = 8,
) -> None:
    grid: list[list[tuple[float, float, float]]] = []
    ca = math.cos(angle)
    sa = math.sin(angle)
    for sx in range(span_segments + 1):
        x = -span * 0.5 + span * sx / span_segments
        row = []
        edge_lift = 0.035 * (abs(x) / max(span * 0.5, 0.001)) ** 2
        for cz in range(chord_segments + 1):
            t = cz / chord_segments
            local_z = (t - 0.5) * chord
            local_y = math.sin(t * math.pi) * camber - edge_lift
            y = y_center + local_y * ca - local_z * sa
            z = z_center + local_z * ca + local_y * sa
            row.append((x, y, z))
        grid.append(row)
    for sx in range(span_segments):
        for cz in range(chord_segments):
            mesh.quad(material, grid[sx][cz], grid[sx + 1][cz], grid[sx + 1][cz + 1], grid[sx][cz + 1])


def build_car() -> Mesh:
    mesh = Mesh()

    def wedge_loft(material: str, sections: list[tuple[float, float, float, float, float]]) -> None:
        rings = []
        for z, half_width, bottom_y, shoulder_y, ridge_y in sections:
            rings.append(
                [
                    (-half_width, bottom_y, z),
                    (half_width, bottom_y, z),
                    (half_width, shoulder_y, z),
                    (0.0, ridge_y, z),
                    (-half_width, shoulder_y, z),
                ]
            )
        for index in range(len(rings) - 1):
            a = rings[index]
            b = rings[index + 1]
            mesh.quad(material, a[0], a[1], b[1], b[0], ((0.0, -1.0, 0.0),) * 4)
            mesh.quad(material, a[1], a[2], b[2], b[1])
            mesh.quad(material, a[2], a[3], b[3], b[2])
            mesh.quad(material, a[3], a[4], b[4], b[3])
            mesh.quad(material, a[4], a[0], b[0], b[4])
        rear = rings[0]
        front = rings[-1]
        mesh.quad(material, rear[0], rear[4], rear[3], rear[1])
        mesh.tri(material, rear[1], rear[3], rear[2])
        mesh.quad(material, front[0], front[1], front[3], front[4])
        mesh.tri(material, front[1], front[2], front[3])

    # Low carbon floor and sharp, flat-panel monocoque. The tub intentionally
    # uses planar facets instead of rounded lofts to avoid the previous blob
    # silhouette.
    box(mesh, "carbon_floor", (-0.86, 0.10, -2.08), (0.86, 0.16, 2.24))
    tub_rear = -1.45
    tub_front = 0.76
    tub_half_width = 0.44
    tub_bottom = 0.12
    tub_shoulder = 0.50
    tub_ridge = 0.58
    mesh.quad(
        "paint_pearl_faceted_tub",
        (-tub_half_width, tub_bottom, tub_rear),
        (tub_half_width, tub_bottom, tub_rear),
        (tub_half_width, tub_bottom, tub_front),
        (-tub_half_width, tub_bottom, tub_front),
        ((0.0, -1.0, 0.0),) * 4,
    )
    mesh.quad(
        "paint_pearl_faceted_tub",
        (tub_half_width, tub_bottom, tub_rear),
        (tub_half_width, tub_shoulder, tub_rear),
        (tub_half_width, tub_shoulder, tub_front),
        (tub_half_width, tub_bottom, tub_front),
        ((1.0, 0.0, 0.0),) * 4,
    )
    mesh.quad(
        "paint_pearl_faceted_tub",
        (-tub_half_width, tub_bottom, tub_front),
        (-tub_half_width, tub_shoulder, tub_front),
        (-tub_half_width, tub_shoulder, tub_rear),
        (-tub_half_width, tub_bottom, tub_rear),
        ((-1.0, 0.0, 0.0),) * 4,
    )
    for z0, z1 in ((tub_rear, -0.72), (0.08, tub_front)):
        mesh.quad(
            "paint_pearl_faceted_tub",
            (-tub_half_width, tub_shoulder, z0),
            (0.0, tub_ridge, z0),
            (0.0, tub_ridge, z1),
            (-tub_half_width, tub_shoulder, z1),
        )
        mesh.quad(
            "paint_pearl_faceted_tub",
            (0.0, tub_ridge, z0),
            (tub_half_width, tub_shoulder, z0),
            (tub_half_width, tub_shoulder, z1),
            (0.0, tub_ridge, z1),
        )
    box(mesh, "paint_pearl_cockpit_left_rail", (-0.48, 0.48, -0.76), (-0.26, 0.58, 0.16))
    box(mesh, "paint_pearl_cockpit_right_rail", (0.26, 0.48, -0.76), (0.48, 0.58, 0.16))
    box(mesh, "paint_dark_cockpit_void", (-0.24, 0.46, -0.70), (0.24, 0.52, 0.10))

    wedge_loft(
        "paint_pearl_low_wedge_nose",
        [
            (0.74, 0.38, 0.13, 0.40, 0.47),
            (1.12, 0.30, 0.13, 0.34, 0.39),
            (1.55, 0.20, 0.13, 0.27, 0.30),
            (2.08, 0.075, 0.195, 0.235, 0.245),
        ],
    )
    box(mesh, "carbon_front_wing_mount", (-0.16, 0.185, 1.92), (0.16, 0.245, 2.15))

    def sidepod(side: float) -> None:
        inner = side * 0.34
        outer = side * 0.72
        front_z = 0.35
        rear_z = -1.30
        bottom = 0.12
        front_top = 0.46
        rear_top = 0.15
        outward = (side, 0.0, 0.0)
        inward = (-side, 0.0, 0.0)
        mesh.quad(
            "paint_pearl_wedge_sidepod",
            (inner, bottom, front_z),
            (outer, bottom, front_z),
            (outer, front_top, front_z),
            (inner, front_top, front_z),
            ((0.0, 0.0, 1.0),) * 4,
        )
        mesh.quad(
            "paint_pearl_wedge_sidepod",
            (outer, bottom, rear_z),
            (outer, rear_top, rear_z),
            (outer, front_top, front_z),
            (outer, bottom, front_z),
            (outward,) * 4,
        )
        mesh.quad(
            "paint_pearl_wedge_sidepod",
            (inner, bottom, front_z),
            (inner, front_top, front_z),
            (inner, rear_top, rear_z),
            (inner, bottom, rear_z),
            (inward,) * 4,
        )
        mesh.quad(
            "paint_pearl_wedge_sidepod",
            (inner, front_top, front_z),
            (outer, front_top, front_z),
            (outer, rear_top, rear_z),
            (inner, rear_top, rear_z),
        )
        mesh.quad(
            "paint_pearl_wedge_sidepod",
            (inner, bottom, rear_z),
            (outer, bottom, rear_z),
            (outer, bottom, front_z),
            (inner, bottom, front_z),
            ((0.0, -1.0, 0.0),) * 4,
        )
        mesh.quad(
            "paint_dark_radiator_inlet",
            (side * 0.41, 0.20, front_z + 0.004),
            (side * 0.66, 0.20, front_z + 0.004),
            (side * 0.66, 0.39, front_z + 0.004),
            (side * 0.41, 0.39, front_z + 0.004),
            ((0.0, 0.0, 1.0),) * 4,
        )
        for fin in range(7):
            y = 0.225 + fin * 0.027
            box(mesh, "metal_radiator_fins", (side * 0.43, y, front_z + 0.010), (side * 0.64, y + 0.006, front_z + 0.030))
        box(mesh, "carbon_bargeboard", (side * 0.48, 0.11, 0.48), (side * 0.56, 0.66, 0.70))

    sidepod(-1.0)
    sidepod(1.0)

    wedge_loft(
        "paint_dark_engine_cover",
        [
            (-1.72, 0.24, 0.48, 0.62, 0.84),
            (-1.18, 0.30, 0.48, 0.68, 0.95),
            (-0.55, 0.22, 0.50, 0.66, 0.84),
            (-0.20, 0.12, 0.50, 0.58, 0.66),
        ],
    )
    mesh.quad(
        "paint_dark_shark_fin",
        (-0.028, 0.68, -1.66),
        (-0.028, 1.12, -1.08),
        (-0.028, 0.86, -0.36),
        (-0.028, 0.58, -0.18),
    )
    mesh.quad(
        "paint_dark_shark_fin",
        (0.028, 0.58, -0.18),
        (0.028, 0.86, -0.36),
        (0.028, 1.12, -1.08),
        (0.028, 0.68, -1.66),
    )
    wedge_loft(
        "carbon_airbox_scoop",
        [
            (-0.72, 0.18, 0.82, 0.96, 1.08),
            (-0.48, 0.14, 0.86, 1.04, 1.16),
            (-0.28, 0.08, 0.90, 0.98, 1.04),
        ],
    )
    box(mesh, "paint_accent_spine_stripe", (-0.050, 0.585, 0.04), (0.050, 0.620, 0.74))
    box(mesh, "paint_accent_spine_stripe", (-0.038, 0.235, 1.05), (0.038, 0.268, 2.00))

    wing_panel(mesh, "carbon_front_wing_main", 2.64, 0.14, 3.18, 0.46, 0.018, -0.06, 28, 5)
    wing_panel(mesh, "carbon_front_wing_upper_flap", 2.88, 0.27, 2.86, 0.32, 0.014, -0.12, 24, 4)
    wing_panel(mesh, "carbon_front_wing_cascade", 2.36, 0.31, 2.26, 0.24, 0.012, -0.22, 18, 3)
    box(mesh, "carbon_front_endplate_left", (-1.68, 0.04, 2.34), (-1.54, 0.50, 3.06))
    box(mesh, "carbon_front_endplate_right", (1.54, 0.04, 2.34), (1.68, 0.50, 3.06))

    wing_panel(mesh, "carbon_rear_wing_main", -2.16, 0.98, 2.34, 0.38, 0.016, 0.05, 24, 5)
    wing_panel(mesh, "carbon_rear_wing_drs_flap", -1.94, 1.17, 2.12, 0.28, 0.012, 0.02, 20, 4)
    box(mesh, "carbon_rear_endplate_left", (-1.28, 0.72, -2.46), (-1.10, 1.38, -1.72))
    box(mesh, "carbon_rear_endplate_right", (1.10, 0.72, -2.46), (1.28, 1.38, -1.72))
    cylinder_between(mesh, "carbon_rear_wing_pillar", (-0.24, 0.52, -1.76), (-0.24, 1.05, -2.05), 0.035, 14)
    cylinder_between(mesh, "carbon_rear_wing_pillar", (0.24, 0.52, -1.76), (0.24, 1.05, -2.05), 0.035, 14)

    for side in (-1.0, 1.0):
        for fin in range(4):
            z0 = -2.00 + fin * 0.22
            box(mesh, "carbon_diffuser_fin", (side * 0.18 + side * fin * 0.11, 0.12, z0), (side * 0.23 + side * fin * 0.11, 0.46, z0 + 0.62))
        box(mesh, "carbon_floor_strake", (side * 0.48, 0.14, -1.65), (side * 0.55, 0.34, 0.80))

    wheel_hubs = [
        (-1.02, 0.34, 1.27),
        (1.02, 0.34, 1.27),
        (-1.05, 0.34, -1.02),
        (1.05, 0.34, -1.02),
    ]
    for x, y, z in wheel_hubs:
        side = -1.0 if x < 0 else 1.0
        chassis_front = 0.48 if z > 0.0 else -0.62
        for dy in (-0.06, 0.16):
            cylinder_between(mesh, "suspension_metal_wishbone", (side * 0.28, 0.37 + dy, chassis_front + 0.22), (x, y + dy, z + 0.18), 0.020, 12)
            cylinder_between(mesh, "suspension_metal_wishbone", (side * 0.28, 0.37 + dy, chassis_front - 0.22), (x, y + dy, z - 0.18), 0.020, 12)
        cylinder_between(mesh, "suspension_metal_pushrod", (side * 0.20, 0.70, chassis_front), (x, y + 0.10, z), 0.017, 12)
        uv_sphere(mesh, "metal_joint_bracket", (x, y + 0.04, z), (0.055, 0.055, 0.055), 8, 16)

    cylinder_between(mesh, "carbon_halo", (-0.34, 0.76, 0.16), (0.0, 1.16, -0.10), 0.045, 18)
    cylinder_between(mesh, "carbon_halo", (0.34, 0.76, 0.16), (0.0, 1.16, -0.10), 0.045, 18)
    cylinder_between(mesh, "carbon_halo", (0.0, 1.16, -0.10), (0.0, 0.77, -0.88), 0.052, 18)
    cylinder_between(mesh, "carbon_halo", (-0.44, 0.78, -0.72), (0.44, 0.78, -0.72), 0.040, 18)

    uv_sphere(mesh, "paint_dark_helmet", (0.0, 0.74, -0.50), (0.20, 0.21, 0.20), 18, 32)
    uv_sphere(mesh, "visor_glass", (0.0, 0.76, -0.33), (0.16, 0.075, 0.09), 8, 20, 0.05, math.pi - 0.05, -0.15, 0.42)

    for side in (-1.0, 1.0):
        cylinder_between(mesh, "metal_mirror_stalk", (side * 0.44, 0.64, 0.30), (side * 0.72, 0.70, 0.50), 0.018, 10)
        uv_sphere(mesh, "paint_dark_mirror", (side * 0.80, 0.72, 0.55), (0.12, 0.055, 0.075), 8, 18)
        cylinder_between(mesh, "metal_exhaust_pipe", (side * 0.18, 0.40, -1.80), (side * 0.22, 0.38, -2.34), 0.055, 18)
    box(mesh, "brake_light_rear", (-0.18, 0.48, -2.32), (0.18, 0.55, -2.28))

    return mesh


def build_wheel() -> Mesh:
    mesh = Mesh()
    segments = 96
    width_profile = [
        (-0.30, 0.300),
        (-0.27, 0.345),
        (-0.22, 0.378),
        (-0.12, 0.392),
        (0.00, 0.398),
        (0.12, 0.392),
        (0.22, 0.378),
        (0.27, 0.345),
        (0.30, 0.300),
    ]
    rings = []
    for x, radius in width_profile:
        ring = []
        radius_dx = x / 0.30 * 0.42
        for index in range(segments):
            theta = math.tau * index / segments
            position = (x, math.cos(theta) * radius, math.sin(theta) * radius)
            normal = norm((radius_dx, math.cos(theta), math.sin(theta)))
            ring.append((position, normal))
        rings.append(ring)
    for ring_index in range(len(rings) - 1):
        for index in range(segments):
            next_index = (index + 1) % segments
            a, na = rings[ring_index][index]
            b, nb = rings[ring_index + 1][index]
            c, nc = rings[ring_index + 1][next_index]
            d, nd = rings[ring_index][next_index]
            mesh.quad("tire_rubber", a, b, c, d, (na, nb, nc, nd))

    cylinder_between(mesh, "rim_metal_lip", (-0.245, 0.0, 0.0), (-0.185, 0.0, 0.0), 0.258, 64)
    cylinder_between(mesh, "rim_metal_lip", (0.185, 0.0, 0.0), (0.245, 0.0, 0.0), 0.258, 64)
    cylinder_between(mesh, "rim_metal_inner_barrel", (-0.185, 0.0, 0.0), (0.185, 0.0, 0.0), 0.208, 64)
    cylinder_between(mesh, "brake_disc_metal", (-0.035, 0.0, 0.0), (0.035, 0.0, 0.0), 0.215, 64)
    cylinder_between(mesh, "hub_metal_center", (-0.075, 0.0, 0.0), (0.075, 0.0, 0.0), 0.112, 48)
    cylinder_between(mesh, "wheel_nut_metal", (-0.115, 0.0, 0.0), (0.115, 0.0, 0.0), 0.055, 6)

    for index in range(10):
        theta = math.tau * index / 10
        for offset in (-0.026, 0.026):
            radial = (0.0, math.cos(theta + offset), math.sin(theta + offset))
            start = (0.085, radial[1] * 0.11, radial[2] * 0.11)
            end = (0.225, radial[1] * 0.245, radial[2] * 0.245)
            cylinder_between(mesh, "spoke_metal_dual", start, end, 0.018, 10)
    for slot in range(18):
        theta = math.tau * slot / 18
        y = math.cos(theta) * 0.165
        z = math.sin(theta) * 0.165
        box(mesh, "brake_disc_slot", (-0.040, y - 0.010, z - 0.026), (0.040, y + 0.010, z + 0.026))
    box(mesh, "caliper_metal_red", (0.11, 0.145, -0.095), (0.26, 0.255, 0.105))
    return mesh


def build_steering_wheel() -> Mesh:
    mesh = Mesh()
    ring_radius = 0.205
    for side in (-1.0, 1.0):
        cylinder_between(mesh, "rubber_grip", (side * 0.145, -0.090, 0.010), (side * 0.205, 0.105, 0.010), 0.035, 18)
        cylinder_between(mesh, "carbon_yoke", (side * 0.145, -0.080, 0.006), (0.045 * side, -0.010, 0.006), 0.025, 16)
        cylinder_between(mesh, "carbon_yoke", (side * 0.195, 0.080, 0.006), (0.070 * side, 0.030, 0.006), 0.022, 16)
    cylinder_between(mesh, "carbon_top_bridge", (-0.160, 0.120, 0.004), (0.160, 0.120, 0.004), 0.024, 18)
    cylinder_between(mesh, "carbon_bottom_bridge", (-0.118, -0.116, 0.004), (0.118, -0.116, 0.004), 0.024, 18)
    box(mesh, "carbon_lcd_bezel", (-0.116, -0.060, -0.010), (0.116, 0.060, 0.028))
    box(mesh, "visor_glass_lcd", (-0.096, -0.042, 0.026), (0.096, 0.040, 0.034))
    for index, color_name in enumerate(("paint_accent_button", "metal_blue_button", "metal_green_button", "metal_yellow_button")):
        x = -0.082 + index * 0.055
        cylinder_between(mesh, color_name, (x, -0.092, 0.028), (x, -0.092, 0.046), 0.014, 18)
    for side in (-1.0, 1.0):
        cylinder_between(mesh, "metal_rotary_dial", (side * 0.090, 0.085, 0.026), (side * 0.090, 0.085, 0.050), 0.020, 20)
    del ring_radius
    return mesh


def main() -> None:
    meshes = {
        "car.obj": build_car(),
        "wheel.obj": build_wheel(),
        "steering_wheel.obj": build_steering_wheel(),
    }
    for name, mesh in meshes.items():
        path = MESH_DIR / name
        mesh.write(path)
        print(f"wrote {path.relative_to(ROOT)}: {len(mesh.vertices)} vertices, {len(mesh.faces)} triangles")


if __name__ == "__main__":
    main()
